/// Built-in MQL5 functions, types, constants, and keywords.
/// This provides autocomplete and hover documentation for the MQL5 standard API.

#[derive(Clone, Debug)]
pub struct Builtin {
    pub name: &'static str,
    pub kind: BuiltinKind,
    pub signature: &'static str,
    pub doc: Option<&'static str>,
}

#[derive(Clone, Debug)]
pub enum BuiltinKind {
    Function,
    Constant,
    Type,
    Keyword,
    Variable,
}

impl Builtin {
    /// Generate snippet insert text for functions.
    pub fn insert_text(&self) -> String {
        match self.kind {
            BuiltinKind::Function => {
                // Extract params from signature to create snippet
                if let Some(paren_start) = self.signature.find('(') {
                    let before_paren = &self.signature[..paren_start];
                    let name = before_paren.split_whitespace().last().unwrap_or(self.name);
                    let params_part = &self.signature[paren_start + 1..];
                    if let Some(paren_end) = params_part.find(')') {
                        let params = &params_part[..paren_end];
                        if params.trim().is_empty() {
                            return format!("{}()", name);
                        }
                        // Create snippet placeholders
                        let parts: Vec<&str> = params.split(',').collect();
                        let snippets: Vec<String> = parts
                            .iter()
                            .enumerate()
                            .map(|(i, p)| format!("${{{}: {}}}", i + 1, p.trim()))
                            .collect();
                        return format!("{}({})", name, snippets.join(", "));
                    }
                }
                self.name.to_string()
            }
            _ => self.name.to_string(),
        }
    }
}

/// Core MQL5 built-in definitions.
/// This is a curated subset of the most commonly used functions.
pub static MQL5_BUILTINS: &[Builtin] = &[
    // ── Trading Functions ──
    Builtin { name: "OrderSend", kind: BuiltinKind::Function,
        signature: "bool OrderSend(MqlTradeRequest &request, MqlTradeResult &result)",
        doc: Some("Sends a trade request to the server. Returns true on success.") },
    Builtin { name: "OrderCalcMargin", kind: BuiltinKind::Function,
        signature: "bool OrderCalcMargin(ENUM_ORDER_TYPE action, string symbol, double volume, double price, double &margin)",
        doc: Some("Calculates the margin required for the specified order.") },
    Builtin { name: "OrderCalcProfit", kind: BuiltinKind::Function,
        signature: "bool OrderCalcProfit(ENUM_ORDER_TYPE action, string symbol, double volume, double price_open, double price_close, double &profit)",
        doc: Some("Calculates the profit for the specified order.") },
    Builtin { name: "OrdersTotal", kind: BuiltinKind::Function,
        signature: "int OrdersTotal()",
        doc: Some("Returns the number of current pending orders.") },
    Builtin { name: "OrderSelect", kind: BuiltinKind::Function,
        signature: "bool OrderSelect(ulong ticket)",
        doc: Some("Selects an order for further work by ticket.") },
    Builtin { name: "OrderGetInteger", kind: BuiltinKind::Function,
        signature: "long OrderGetInteger(ENUM_ORDER_PROPERTY_INTEGER property_id)",
        doc: Some("Returns the requested integer property of the selected order.") },
    Builtin { name: "OrderGetDouble", kind: BuiltinKind::Function,
        signature: "double OrderGetDouble(ENUM_ORDER_PROPERTY_DOUBLE property_id)",
        doc: Some("Returns the requested double property of the selected order.") },
    Builtin { name: "OrderGetString", kind: BuiltinKind::Function,
        signature: "string OrderGetString(ENUM_ORDER_PROPERTY_STRING property_id)",
        doc: Some("Returns the requested string property of the selected order.") },
    Builtin { name: "OrderGetTicket", kind: BuiltinKind::Function,
        signature: "ulong OrderGetTicket(int index)",
        doc: Some("Returns the ticket of the pending order by index.") },

    // ── Position Functions ──
    Builtin { name: "PositionSelect", kind: BuiltinKind::Function,
        signature: "bool PositionSelect(string symbol)",
        doc: Some("Selects an open position by symbol for further work.") },
    Builtin { name: "PositionSelectByTicket", kind: BuiltinKind::Function,
        signature: "bool PositionSelectByTicket(ulong ticket)",
        doc: Some("Selects an open position by ticket for further work.") },
    Builtin { name: "PositionsTotal", kind: BuiltinKind::Function,
        signature: "int PositionsTotal()",
        doc: Some("Returns the number of current open positions.") },
    Builtin { name: "PositionGetInteger", kind: BuiltinKind::Function,
        signature: "long PositionGetInteger(ENUM_POSITION_PROPERTY_INTEGER property_id)",
        doc: Some("Returns the requested integer property of the selected position.") },
    Builtin { name: "PositionGetDouble", kind: BuiltinKind::Function,
        signature: "double PositionGetDouble(ENUM_POSITION_PROPERTY_DOUBLE property_id)",
        doc: Some("Returns the requested double property of the selected position.") },
    Builtin { name: "PositionGetString", kind: BuiltinKind::Function,
        signature: "string PositionGetString(ENUM_POSITION_PROPERTY_STRING property_id)",
        doc: Some("Returns the requested string property of the selected position.") },
    Builtin { name: "PositionGetSymbol", kind: BuiltinKind::Function,
        signature: "string PositionGetSymbol(int index)",
        doc: Some("Returns the symbol of the open position by index.") },
    Builtin { name: "PositionGetTicket", kind: BuiltinKind::Function,
        signature: "ulong PositionGetTicket(int index)",
        doc: Some("Returns the ticket of the open position by index.") },

    // ── History Functions ──
    Builtin { name: "HistorySelect", kind: BuiltinKind::Function,
        signature: "bool HistorySelect(datetime from_date, datetime to_date)",
        doc: Some("Requests the history of deals and orders for the specified period.") },
    Builtin { name: "HistoryOrdersTotal", kind: BuiltinKind::Function,
        signature: "int HistoryOrdersTotal()",
        doc: Some("Returns the number of orders in the history.") },
    Builtin { name: "HistoryDealsTotal", kind: BuiltinKind::Function,
        signature: "int HistoryDealsTotal()",
        doc: Some("Returns the number of deals in the history.") },

    // ── Technical Indicators ──
    Builtin { name: "iRSI", kind: BuiltinKind::Function,
        signature: "int iRSI(string symbol, ENUM_TIMEFRAMES period, int ma_period, ENUM_APPLIED_PRICE applied_price)",
        doc: Some("Creates RSI indicator handle. Use CopyBuffer() to get values.") },
    Builtin { name: "iMA", kind: BuiltinKind::Function,
        signature: "int iMA(string symbol, ENUM_TIMEFRAMES period, int ma_period, int ma_shift, ENUM_MA_METHOD ma_method, ENUM_APPLIED_PRICE applied_price)",
        doc: Some("Creates Moving Average indicator handle.") },
    Builtin { name: "iMACD", kind: BuiltinKind::Function,
        signature: "int iMACD(string symbol, ENUM_TIMEFRAMES period, int fast_ema, int slow_ema, int signal_period, ENUM_APPLIED_PRICE applied_price)",
        doc: Some("Creates MACD indicator handle.") },
    Builtin { name: "iBands", kind: BuiltinKind::Function,
        signature: "int iBands(string symbol, ENUM_TIMEFRAMES period, int bands_period, int bands_shift, double deviation, ENUM_APPLIED_PRICE applied_price)",
        doc: Some("Creates Bollinger Bands indicator handle.") },
    Builtin { name: "iATR", kind: BuiltinKind::Function,
        signature: "int iATR(string symbol, ENUM_TIMEFRAMES period, int ma_period)",
        doc: Some("Creates ATR indicator handle.") },
    Builtin { name: "iStochastic", kind: BuiltinKind::Function,
        signature: "int iStochastic(string symbol, ENUM_TIMEFRAMES period, int Kperiod, int Dperiod, int slowing, ENUM_MA_METHOD ma_method, ENUM_STO_PRICE price_field)",
        doc: Some("Creates Stochastic indicator handle.") },
    Builtin { name: "iCustom", kind: BuiltinKind::Function,
        signature: "int iCustom(string symbol, ENUM_TIMEFRAMES period, string name, ...)",
        doc: Some("Creates a custom indicator handle. Parameters after name are indicator inputs.") },

    // ── Chart Functions ──
    Builtin { name: "ChartOpen", kind: BuiltinKind::Function,
        signature: "long ChartOpen(string symbol, ENUM_TIMEFRAMES period)",
        doc: Some("Opens a new chart with the specified symbol and period.") },
    Builtin { name: "ChartClose", kind: BuiltinKind::Function,
        signature: "bool ChartClose(long chart_id=0)",
        doc: Some("Closes the specified chart.") },
    Builtin { name: "ChartRedraw", kind: BuiltinKind::Function,
        signature: "void ChartRedraw(long chart_id=0)",
        doc: Some("Forces chart redraw. Call after modifying chart objects.") },
    Builtin { name: "ChartSetInteger", kind: BuiltinKind::Function,
        signature: "bool ChartSetInteger(long chart_id, ENUM_CHART_PROPERTY_INTEGER prop_id, long value)",
        doc: Some("Sets an integer property of the chart.") },
    Builtin { name: "ChartGetInteger", kind: BuiltinKind::Function,
        signature: "long ChartGetInteger(long chart_id, ENUM_CHART_PROPERTY_INTEGER prop_id, int sub_window=0)",
        doc: Some("Returns an integer property of the chart.") },
    Builtin { name: "ChartSetDouble", kind: BuiltinKind::Function,
        signature: "bool ChartSetDouble(long chart_id, ENUM_CHART_PROPERTY_DOUBLE prop_id, double value)",
        doc: Some("Sets a double property of the chart.") },
    Builtin { name: "ChartGetDouble", kind: BuiltinKind::Function,
        signature: "double ChartGetDouble(long chart_id, ENUM_CHART_PROPERTY_DOUBLE prop_id, int sub_window=0)",
        doc: Some("Returns a double property of the chart.") },
    Builtin { name: "ChartTimePriceToXY", kind: BuiltinKind::Function,
        signature: "bool ChartTimePriceToXY(long chart_id, int sub_window, datetime time, double price, int &x, int &y)",
        doc: Some("Converts time/price to chart window X/Y coordinates.") },
    Builtin { name: "ChartXYToTimePrice", kind: BuiltinKind::Function,
        signature: "bool ChartXYToTimePrice(long chart_id, int x, int y, int &sub_window, datetime &time, double &price)",
        doc: Some("Converts chart window X/Y coordinates to time/price.") },
    Builtin { name: "ChartNavigate", kind: BuiltinKind::Function,
        signature: "bool ChartNavigate(long chart_id, ENUM_CHART_POSITION position, int shift=0)",
        doc: Some("Navigates the chart by shifting the specified number of bars.") },
    Builtin { name: "ChartID", kind: BuiltinKind::Function,
        signature: "long ChartID()",
        doc: Some("Returns the ID of the current chart.") },

    // ── Object Functions ──
    Builtin { name: "ObjectCreate", kind: BuiltinKind::Function,
        signature: "bool ObjectCreate(long chart_id, string name, ENUM_OBJECT type, int sub_window, datetime time1, double price1, ...)",
        doc: Some("Creates a graphical object on the chart.") },
    Builtin { name: "ObjectDelete", kind: BuiltinKind::Function,
        signature: "bool ObjectDelete(long chart_id, string name)",
        doc: Some("Deletes a graphical object from the chart by name.") },
    Builtin { name: "ObjectFind", kind: BuiltinKind::Function,
        signature: "int ObjectFind(long chart_id, string name)",
        doc: Some("Searches for an object by name. Returns sub-window index or -1.") },
    Builtin { name: "ObjectSetInteger", kind: BuiltinKind::Function,
        signature: "bool ObjectSetInteger(long chart_id, string name, ENUM_OBJECT_PROPERTY_INTEGER prop_id, long prop_value)",
        doc: Some("Sets an integer property of a graphical object.") },
    Builtin { name: "ObjectGetInteger", kind: BuiltinKind::Function,
        signature: "long ObjectGetInteger(long chart_id, string name, ENUM_OBJECT_PROPERTY_INTEGER prop_id)",
        doc: Some("Returns an integer property of a graphical object.") },
    Builtin { name: "ObjectSetDouble", kind: BuiltinKind::Function,
        signature: "bool ObjectSetDouble(long chart_id, string name, ENUM_OBJECT_PROPERTY_DOUBLE prop_id, double prop_value)",
        doc: Some("Sets a double property of a graphical object.") },
    Builtin { name: "ObjectGetDouble", kind: BuiltinKind::Function,
        signature: "double ObjectGetDouble(long chart_id, string name, ENUM_OBJECT_PROPERTY_DOUBLE prop_id)",
        doc: Some("Returns a double property of a graphical object.") },
    Builtin { name: "ObjectSetString", kind: BuiltinKind::Function,
        signature: "bool ObjectSetString(long chart_id, string name, ENUM_OBJECT_PROPERTY_STRING prop_id, string prop_value)",
        doc: Some("Sets a string property of a graphical object.") },
    Builtin { name: "ObjectGetString", kind: BuiltinKind::Function,
        signature: "string ObjectGetString(long chart_id, string name, ENUM_OBJECT_PROPERTY_STRING prop_id)",
        doc: Some("Returns a string property of a graphical object.") },
    Builtin { name: "ObjectsTotal", kind: BuiltinKind::Function,
        signature: "int ObjectsTotal(long chart_id, int sub_window=-1, int type=-1)",
        doc: Some("Returns the total number of objects on the chart.") },
    Builtin { name: "ObjectsDeleteAll", kind: BuiltinKind::Function,
        signature: "int ObjectsDeleteAll(long chart_id, int sub_window=-1, int type=-1)",
        doc: Some("Deletes all objects from the chart. Returns number deleted.") },

    // ── Array Functions ──
    Builtin { name: "ArraySize", kind: BuiltinKind::Function,
        signature: "int ArraySize(const void &array[])",
        doc: Some("Returns the number of elements in the array.") },
    Builtin { name: "ArrayResize", kind: BuiltinKind::Function,
        signature: "int ArrayResize(void &array[], int new_size, int reserve_size=0)",
        doc: Some("Resizes the array. Returns new size or -1 on failure.") },
    Builtin { name: "ArrayCopy", kind: BuiltinKind::Function,
        signature: "int ArrayCopy(void &dst_array[], const void &src_array[], int dst_start=0, int src_start=0, int count=WHOLE_ARRAY)",
        doc: Some("Copies elements from one array to another.") },
    Builtin { name: "ArraySort", kind: BuiltinKind::Function,
        signature: "bool ArraySort(void &array[])",
        doc: Some("Sorts a numeric array in ascending order.") },
    Builtin { name: "ArraySetAsSeries", kind: BuiltinKind::Function,
        signature: "bool ArraySetAsSeries(void &array[], bool flag)",
        doc: Some("Sets array indexing direction. true = newest element at [0].") },
    Builtin { name: "ArrayInitialize", kind: BuiltinKind::Function,
        signature: "int ArrayInitialize(void &array[], void value)",
        doc: Some("Fills all elements of the array with the specified value.") },
    Builtin { name: "ArrayFree", kind: BuiltinKind::Function,
        signature: "void ArrayFree(void &array[])",
        doc: Some("Frees the memory used by a dynamic array.") },

    // ── Copy Functions ──
    Builtin { name: "CopyBuffer", kind: BuiltinKind::Function,
        signature: "int CopyBuffer(int indicator_handle, int buffer_num, int start_pos, int count, double &buffer[])",
        doc: Some("Copies indicator buffer data to an array. Returns number of copied elements.") },
    Builtin { name: "CopyRates", kind: BuiltinKind::Function,
        signature: "int CopyRates(string symbol, ENUM_TIMEFRAMES period, int start_pos, int count, MqlRates &rates[])",
        doc: Some("Copies price history (OHLCV) to an MqlRates array.") },
    Builtin { name: "CopyTime", kind: BuiltinKind::Function,
        signature: "int CopyTime(string symbol, ENUM_TIMEFRAMES period, int start_pos, int count, datetime &time_array[])",
        doc: Some("Copies bar open times to an array.") },
    Builtin { name: "CopyOpen", kind: BuiltinKind::Function,
        signature: "int CopyOpen(string symbol, ENUM_TIMEFRAMES period, int start_pos, int count, double &open_array[])",
        doc: Some("Copies bar open prices to an array.") },
    Builtin { name: "CopyHigh", kind: BuiltinKind::Function,
        signature: "int CopyHigh(string symbol, ENUM_TIMEFRAMES period, int start_pos, int count, double &high_array[])",
        doc: Some("Copies bar high prices to an array.") },
    Builtin { name: "CopyLow", kind: BuiltinKind::Function,
        signature: "int CopyLow(string symbol, ENUM_TIMEFRAMES period, int start_pos, int count, double &low_array[])",
        doc: Some("Copies bar low prices to an array.") },
    Builtin { name: "CopyClose", kind: BuiltinKind::Function,
        signature: "int CopyClose(string symbol, ENUM_TIMEFRAMES period, int start_pos, int count, double &close_array[])",
        doc: Some("Copies bar close prices to an array.") },
    Builtin { name: "CopyTicks", kind: BuiltinKind::Function,
        signature: "int CopyTicks(string symbol, MqlTick &ticks[], uint flags=COPY_TICKS_ALL, ulong from=0, uint count=0)",
        doc: Some("Copies tick data to an MqlTick array.") },

    // ── Time Functions ──
    Builtin { name: "TimeCurrent", kind: BuiltinKind::Function,
        signature: "datetime TimeCurrent()",
        doc: Some("Returns the last known server time (time of the last quote).") },
    Builtin { name: "TimeLocal", kind: BuiltinKind::Function,
        signature: "datetime TimeLocal()",
        doc: Some("Returns the local computer time.") },
    Builtin { name: "TimeGMT", kind: BuiltinKind::Function,
        signature: "datetime TimeGMT()",
        doc: Some("Returns the GMT time.") },
    Builtin { name: "TimeTradeServer", kind: BuiltinKind::Function,
        signature: "datetime TimeTradeServer()",
        doc: Some("Returns the current trade server time.") },
    Builtin { name: "PeriodSeconds", kind: BuiltinKind::Function,
        signature: "int PeriodSeconds(ENUM_TIMEFRAMES period=PERIOD_CURRENT)",
        doc: Some("Returns the number of seconds in the specified timeframe period.") },
    Builtin { name: "iTime", kind: BuiltinKind::Function,
        signature: "datetime iTime(string symbol, ENUM_TIMEFRAMES timeframe, int shift)",
        doc: Some("Returns the open time of the bar at the specified shift.") },
    Builtin { name: "iBarShift", kind: BuiltinKind::Function,
        signature: "int iBarShift(string symbol, ENUM_TIMEFRAMES timeframe, datetime time, bool exact=false)",
        doc: Some("Returns the bar index for the specified time.") },

    // ── String Functions ──
    Builtin { name: "StringLen", kind: BuiltinKind::Function,
        signature: "int StringLen(string str)",
        doc: Some("Returns the length of the string.") },
    Builtin { name: "StringFind", kind: BuiltinKind::Function,
        signature: "int StringFind(string str, string value, int start_pos=0)",
        doc: Some("Searches for a substring. Returns position or -1.") },
    Builtin { name: "StringSubstr", kind: BuiltinKind::Function,
        signature: "string StringSubstr(string str, int start_pos, int length=-1)",
        doc: Some("Extracts a substring from the string.") },
    Builtin { name: "StringFormat", kind: BuiltinKind::Function,
        signature: "string StringFormat(string format, ...)",
        doc: Some("Formats a string using printf-style format specifiers.") },
    Builtin { name: "IntegerToString", kind: BuiltinKind::Function,
        signature: "string IntegerToString(long value, int str_len=0, ushort fill_char=' ')",
        doc: Some("Converts an integer to string.") },
    Builtin { name: "DoubleToString", kind: BuiltinKind::Function,
        signature: "string DoubleToString(double value, int digits=8)",
        doc: Some("Converts a double to string with specified decimal places.") },
    Builtin { name: "ShortToString", kind: BuiltinKind::Function,
        signature: "string ShortToString(ushort symbol_code)",
        doc: Some("Converts a Unicode character code to a one-character string.") },
    Builtin { name: "ColorToARGB", kind: BuiltinKind::Function,
        signature: "uint ColorToARGB(color clr, uchar alpha=255)",
        doc: Some("Converts a color value to ARGB format with alpha channel.") },
    Builtin { name: "NormalizeDouble", kind: BuiltinKind::Function,
        signature: "double NormalizeDouble(double value, int digits)",
        doc: Some("Rounds a double to the specified number of decimal places.") },

    // ── Math Functions ──
    Builtin { name: "MathAbs", kind: BuiltinKind::Function,
        signature: "double MathAbs(double value)",
        doc: Some("Returns the absolute value.") },
    Builtin { name: "MathMax", kind: BuiltinKind::Function,
        signature: "double MathMax(double value1, double value2)",
        doc: Some("Returns the larger of two values.") },
    Builtin { name: "MathMin", kind: BuiltinKind::Function,
        signature: "double MathMin(double value1, double value2)",
        doc: Some("Returns the smaller of two values.") },
    Builtin { name: "MathRound", kind: BuiltinKind::Function,
        signature: "double MathRound(double value)",
        doc: Some("Rounds to the nearest integer.") },
    Builtin { name: "MathFloor", kind: BuiltinKind::Function,
        signature: "double MathFloor(double value)",
        doc: Some("Rounds down to the nearest integer.") },
    Builtin { name: "MathCeil", kind: BuiltinKind::Function,
        signature: "double MathCeil(double value)",
        doc: Some("Rounds up to the nearest integer.") },
    Builtin { name: "MathPow", kind: BuiltinKind::Function,
        signature: "double MathPow(double base, double exponent)",
        doc: Some("Returns base raised to the power of exponent.") },
    Builtin { name: "MathSqrt", kind: BuiltinKind::Function,
        signature: "double MathSqrt(double value)",
        doc: Some("Returns the square root.") },
    Builtin { name: "MathLog", kind: BuiltinKind::Function,
        signature: "double MathLog(double value)",
        doc: Some("Returns the natural logarithm.") },

    // ── File Functions ──
    Builtin { name: "FileOpen", kind: BuiltinKind::Function,
        signature: "int FileOpen(string file_name, int open_flags, short delimiter='\\t', uint codepage=CP_ACP)",
        doc: Some("Opens a file. Returns handle or INVALID_HANDLE.") },
    Builtin { name: "FileClose", kind: BuiltinKind::Function,
        signature: "void FileClose(int file_handle)",
        doc: Some("Closes a previously opened file.") },
    Builtin { name: "FileWriteString", kind: BuiltinKind::Function,
        signature: "uint FileWriteString(int file_handle, string text, int length=-1)",
        doc: Some("Writes a string to a file.") },
    Builtin { name: "FileReadString", kind: BuiltinKind::Function,
        signature: "string FileReadString(int file_handle, int length=-1)",
        doc: Some("Reads a string from a file.") },
    Builtin { name: "FileIsExist", kind: BuiltinKind::Function,
        signature: "bool FileIsExist(string file_name, int common_flag=0)",
        doc: Some("Checks if a file exists.") },
    Builtin { name: "FileDelete", kind: BuiltinKind::Function,
        signature: "bool FileDelete(string file_name, int common_flag=0)",
        doc: Some("Deletes a file.") },

    // ── GlobalVariable Functions ──
    Builtin { name: "GlobalVariableSet", kind: BuiltinKind::Function,
        signature: "datetime GlobalVariableSet(string name, double value)",
        doc: Some("Sets a global variable value. Creates it if it doesn't exist.") },
    Builtin { name: "GlobalVariableGet", kind: BuiltinKind::Function,
        signature: "double GlobalVariableGet(string name)",
        doc: Some("Returns the value of a global variable.") },
    Builtin { name: "GlobalVariableCheck", kind: BuiltinKind::Function,
        signature: "bool GlobalVariableCheck(string name)",
        doc: Some("Checks if a global variable exists.") },
    Builtin { name: "GlobalVariableDel", kind: BuiltinKind::Function,
        signature: "bool GlobalVariableDel(string name)",
        doc: Some("Deletes a global variable.") },
    Builtin { name: "GlobalVariableSetOnCondition", kind: BuiltinKind::Function,
        signature: "bool GlobalVariableSetOnCondition(string name, double value, double check_value)",
        doc: Some("Atomically sets a GV to value only if its current value equals check_value. Useful for mutex/lock patterns.") },
    Builtin { name: "GlobalVariableTemp", kind: BuiltinKind::Function,
        signature: "bool GlobalVariableTemp(string name)",
        doc: Some("Makes a global variable temporary (deleted when terminal closes).") },

    // ── Misc Functions ──
    Builtin { name: "Print", kind: BuiltinKind::Function,
        signature: "void Print(...)",
        doc: Some("Prints a message to the Experts tab in the terminal.") },
    Builtin { name: "PrintFormat", kind: BuiltinKind::Function,
        signature: "void PrintFormat(string format, ...)",
        doc: Some("Prints a formatted message (printf-style) to the Experts tab.") },
    Builtin { name: "Alert", kind: BuiltinKind::Function,
        signature: "void Alert(...)",
        doc: Some("Displays a dialog box with a message and plays an alert sound.") },
    Builtin { name: "Comment", kind: BuiltinKind::Function,
        signature: "void Comment(...)",
        doc: Some("Displays a comment in the upper-left corner of the chart.") },
    Builtin { name: "GetLastError", kind: BuiltinKind::Function,
        signature: "int GetLastError()",
        doc: Some("Returns the last error code and resets the error variable.") },
    Builtin { name: "ResetLastError", kind: BuiltinKind::Function,
        signature: "void ResetLastError()",
        doc: Some("Resets the last error code to 0.") },
    Builtin { name: "Sleep", kind: BuiltinKind::Function,
        signature: "void Sleep(int milliseconds)",
        doc: Some("Suspends execution for the specified number of milliseconds. Only in EAs.") },
    Builtin { name: "GetTickCount", kind: BuiltinKind::Function,
        signature: "uint GetTickCount()",
        doc: Some("Returns the number of milliseconds since system start.") },
    Builtin { name: "GetTickCount64", kind: BuiltinKind::Function,
        signature: "ulong GetTickCount64()",
        doc: Some("Returns the number of milliseconds since system start (64-bit).") },
    Builtin { name: "GetMicrosecondCount", kind: BuiltinKind::Function,
        signature: "ulong GetMicrosecondCount()",
        doc: Some("Returns the number of microseconds elapsed since MQL5 program start.") },
    Builtin { name: "ExpertRemove", kind: BuiltinKind::Function,
        signature: "void ExpertRemove()",
        doc: Some("Stops the Expert Advisor and removes it from the chart.") },
    Builtin { name: "IsStopped", kind: BuiltinKind::Function,
        signature: "bool IsStopped()",
        doc: Some("Checks if the MQL5 program has been forced to stop.") },
    Builtin { name: "IsTesting", kind: BuiltinKind::Function,
        signature: "bool IsTesting()",
        doc: Some("Checks if the program is running in the Strategy Tester.") },
    Builtin { name: "IsOptimization", kind: BuiltinKind::Function,
        signature: "bool IsOptimization()",
        doc: Some("Checks if the program is running in optimization mode.") },
    Builtin { name: "IsVisualMode", kind: BuiltinKind::Function,
        signature: "bool IsVisualMode()",
        doc: Some("Checks if the Strategy Tester is running in visual mode.") },

    // ── Symbol/Account Info ──
    Builtin { name: "Symbol", kind: BuiltinKind::Function,
        signature: "string Symbol()",
        doc: Some("Returns the current chart symbol name.") },
    Builtin { name: "Period", kind: BuiltinKind::Function,
        signature: "ENUM_TIMEFRAMES Period()",
        doc: Some("Returns the current chart timeframe.") },
    Builtin { name: "Digits", kind: BuiltinKind::Function,
        signature: "int Digits()",
        doc: Some("Returns the number of decimal digits for the current symbol.") },
    Builtin { name: "Point", kind: BuiltinKind::Function,
        signature: "double Point()",
        doc: Some("Returns the point value for the current symbol.") },
    Builtin { name: "SymbolInfoInteger", kind: BuiltinKind::Function,
        signature: "long SymbolInfoInteger(string symbol, ENUM_SYMBOL_INFO_INTEGER prop_id)",
        doc: Some("Returns an integer property of the symbol.") },
    Builtin { name: "SymbolInfoDouble", kind: BuiltinKind::Function,
        signature: "double SymbolInfoDouble(string symbol, ENUM_SYMBOL_INFO_DOUBLE prop_id)",
        doc: Some("Returns a double property of the symbol (bid, ask, spread, etc.).") },
    Builtin { name: "SymbolInfoString", kind: BuiltinKind::Function,
        signature: "string SymbolInfoString(string symbol, ENUM_SYMBOL_INFO_STRING prop_id)",
        doc: Some("Returns a string property of the symbol.") },
    Builtin { name: "SymbolInfoTick", kind: BuiltinKind::Function,
        signature: "bool SymbolInfoTick(string symbol, MqlTick &tick)",
        doc: Some("Returns the latest tick for the specified symbol.") },
    Builtin { name: "AccountInfoInteger", kind: BuiltinKind::Function,
        signature: "long AccountInfoInteger(ENUM_ACCOUNT_INFO_INTEGER prop_id)",
        doc: Some("Returns an integer property of the account.") },
    Builtin { name: "AccountInfoDouble", kind: BuiltinKind::Function,
        signature: "double AccountInfoDouble(ENUM_ACCOUNT_INFO_DOUBLE prop_id)",
        doc: Some("Returns a double property of the account (balance, equity, margin, etc.).") },

    // ── Event Functions ──
    Builtin { name: "EventSetTimer", kind: BuiltinKind::Function,
        signature: "bool EventSetTimer(int seconds)",
        doc: Some("Sets the timer with the specified interval in seconds.") },
    Builtin { name: "EventSetMillisecondTimer", kind: BuiltinKind::Function,
        signature: "bool EventSetMillisecondTimer(int milliseconds)",
        doc: Some("Sets the timer with the specified interval in milliseconds.") },
    Builtin { name: "EventKillTimer", kind: BuiltinKind::Function,
        signature: "void EventKillTimer()",
        doc: Some("Kills the timer.") },
    Builtin { name: "EventChartCustom", kind: BuiltinKind::Function,
        signature: "bool EventChartCustom(long chart_id, ushort custom_event_id, long lparam, double dparam, string sparam)",
        doc: Some("Generates a custom chart event.") },

    // ── Predefined Variables ──
    Builtin { name: "_Symbol", kind: BuiltinKind::Variable,
        signature: "string _Symbol",
        doc: Some("The symbol name of the current chart.") },
    Builtin { name: "_Period", kind: BuiltinKind::Variable,
        signature: "ENUM_TIMEFRAMES _Period",
        doc: Some("The timeframe of the current chart.") },
    Builtin { name: "_Point", kind: BuiltinKind::Variable,
        signature: "double _Point",
        doc: Some("The point value for the current symbol.") },
    Builtin { name: "_Digits", kind: BuiltinKind::Variable,
        signature: "int _Digits",
        doc: Some("The number of decimal digits for the current symbol price.") },
    Builtin { name: "_LastError", kind: BuiltinKind::Variable,
        signature: "int _LastError",
        doc: Some("The last error code.") },
    Builtin { name: "_UninitReason", kind: BuiltinKind::Variable,
        signature: "int _UninitReason",
        doc: Some("The reason for program uninitialization.") },
    Builtin { name: "_StopFlag", kind: BuiltinKind::Variable,
        signature: "bool _StopFlag",
        doc: Some("Indicates that the program is being forcibly stopped.") },
    Builtin { name: "_RandomSeed", kind: BuiltinKind::Variable,
        signature: "int _RandomSeed",
        doc: Some("The seed for the random number generator.") },

    // ── Keywords ──
    Builtin { name: "input", kind: BuiltinKind::Keyword,
        signature: "input",
        doc: Some("Declares an EA input parameter visible in the Properties dialog.") },
    Builtin { name: "sinput", kind: BuiltinKind::Keyword,
        signature: "sinput",
        doc: Some("Declares a static input parameter (not optimizable in Strategy Tester).") },
];
